services:
  postgres:
    image: postgres:16
    container_name: microloan-platform
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: microloan_platform
    volumes:
        - C:/Users/aravi/Desktop/IdeaProjects/microloan-platform/src/main/resources/db/migration/:/docker-entrypoint-initdb.d/
