apiVersion: v2
name: zea-opc-b03-microloan-platform-aravind
description: A microloan distribution and recovery system
version: 0.0.1-SNAPSHOT
appVersion: 0.0.1
type: application
dependencies:
  - name: common
    version: 1.0.98
    repository: '@chartrepo'