nameOverride: "zea-opc-b03-microloan-platform-aravind"
fullnameOverride: "zea-opc-b03-microloan-platform-aravind"
clusterName: zea-opc-b03-microloan-platform-aravind
hpa:
  enabled: false

replicaCount: 1
image:
  repository: 813361731051.dkr.ecr.ap-south-1.amazonaws.com
  repositoryPath: zea-opc-b03-microloan-platform-aravind
  pullPolicy: IfNotPresent
  tag: 0.0.1-SNAPSHOT

disablePropertiesConfigMap: true

envProperties:
  javaXms: 128M
  javaXmx: 512M
  APP_NAME: zea-opc-b03-microloan-platform-aravind
  KINESIS_ACCESSKEY: vault:secrets/data/zone/common/logging#KINESIS_ACCESSKEY
  KINESIS_SECRETKEY: vault:secrets/data/zone/common/logging#KINESIS_SECRETKEY
  KINESIS_REGION: vault:secrets/data/zone/common/logging#KINESIS_REGION
  LOGGING_PIPELINE: KINESIS_AND_SOUT
  METRIC_LOG_FORMAT: JSON

resources:
  limits:
    memory: 2Gi
  requests:
    cpu: 1
    memory: 1Gi

serviceAccountName: microloan-platform-aravind

service:
  port: 8080
  targetPort: 8080
  healthCheckPath: /health
  livenessProbeInitialDelaySeconds: 60
  readinessProbeInitialDelaySeconds: 60

# Full health check URL: http://<<pod-ip>>:8080/health.check.path
additionalPodAnnotations:
  configmap.reloader.stakater.com/reload: "microloan-platform-aravind-env-configmap"
  health.check.enable: "true"
  health.check.module: http_2xx
  health.check.path: "/health"

serviceMonitor:
  enabled: true

volumeMounts: []

olympusLabels:
  olympusCluster: cluster
  olympusClusterBU: bu
  olympusClusterTeam: team-name
  olympusZone: zone-name
  olympusZoneEnv: zone-env

nodeSelector: {}
tolerations: []
affinity: {}
podSecurityContext: {}
securityContext: {}
volumes: {}