spring.application.name=microloan-platform

postgres.jdbc.url=jdbc:postgresql://localhost:5433/microloan_platform
postgres.jdbc.username=postgres
postgres.jdbc.password=postgres
postgres.jdbc.driver=org.postgresql.Driver
postgres.jdbc.pool.size=20
postgres.jdbc.query.timeout.sec=40
postgres.jdbc.time.between.eviction.runs.millis=30000

certstore.proteus.endpoint=https://sb1-god-cipher.mum1-pp.zetaapps.in/proteus/zeta.in
sessions.proteus.endpoint=https://sb1-god-cipher.mum1-pp.zetaapps.in/proteus/zeta.in

logging.level.org.springframework.boot.autoconfigure=DEBUG
logging.level.org.springframework.boot=DEBUG
logging.level.org.hibernate=ERROR
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n

# Show full stack traces
server.error.include-stacktrace=always
server.error.include-message=always