spring.application.name=microloan-platform

spring.datasource.url=jdbc:postgresql://host.docker.internal:5432/microloan_platform
spring.datasource.username=zeta
spring.datasource.password=zeta
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.connection-timeout=40000
spring.datasource.hikari.validation-timeout=5000
spring.datasource.hikari.time-between-eviction-runs-millis = 30000

certstore.proteus.endpoint=https://sb1-god-cipher.mum1-pp.zetaapps.in/proteus/zeta.in
sessions.proteus.endpoint=https://sb1-god-cipher.mum1-pp.zetaapps.in/proteus/zeta.in