spring.application.name=microloan-platform

logging.level.org.springframework.web=DEBUG
logging.level.root=INFO

spring.datasource.url=jdbc:postgresql://localhost:5432/microloan_platform
spring.datasource.username=zeta
spring.datasource.password=zeta
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.connection-timeout=40000
spring.datasource.hikari.validation-timeout=5000
spring.datasource.hikari.time-between-eviction-runs-millis=30000

certstore.proteus.endpoint=https://sb1-god-cipher.mum1-pp.zetaapps.in/proteus/zeta.in
sessions.proteus.endpoint=https://sb1-god-cipher.mum1-pp.zetaapps.in/proteus/zeta.in

# Atropos Publish Mode (ASYNC or SYNC)
atropos.publish.mode=KINESIS

# Event Topics
event.topic.loan.issued=microloan-loan-issued
event.topic.loan.repayment=microloan-loan-repayment
event.topic.loan.overdue=microloan-loan-overdue
event.topic.loan.cancelled=microloan-loan-cancelled
event.topic.loan.closed=microloan-loan-closed
event.topic.application.approved=microloan-application-approved
event.topic.application.rejected=microloan-application-rejected
publisher.service.base.url=https://publisher-service-appinfra.internal.mum1-pp.zetaapps.in/
atropos.subscription.url=https://atropos-controller-appinfra.internal.mum1-pp.zetaapps.in/api/v1/unauth/tenants/0/registerWebhookSubscription
