spring.application.name=microloan-platform
app.name=${spring.application.name}

logging.level.org.springframework.web=DEBUG

server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5433/microloan_platform
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.connection-timeout=40000
spring.datasource.hikari.validation-timeout=5000
spring.datasource.hikari.time-between-eviction-runs-millis=30000

certstore.proteus.endpoint=https://sb1-god-cipher.mum1-pp.zetaapps.in/proteus/zeta.in
sessions.proteus.endpoint=https://sb1-god-cipher.mum1-pp.zetaapps.in/proteus/zeta.in

# Event Topics
atropos.publish.mode=KINESIS
event.topic.loan.issued=microloan-loan-issued
event.topic.loan.repayment=microloan-loan-repayment
event.topic.loan.overdue=microloan-loan-overdue
event.topic.loan.cancelled=microloan-loan-cancelled
event.topic.loan.closed=microloan-loan-closed
event.topic.application.approved=microloan-application-approved
event.topic.application.rejected=microloan-application-rejected
publisher.service.base.url=https://publisher-service-appinfra.internal.mum1-pp.zetaapps.in/
atropos.subscription.url=https://atropos-controller-appinfra.internal.mum1-pp.zetaapps.in/api/v1/unauth/tenants/0/registerWebhookSubscription


logging.level.org.springframework.boot.autoconfigure=DEBUG
logging.level.org.hibernate=ERROR
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n
logging.level.org.springframework.boot=DEBUG
logging.level.org.springframework.jdbc=DEBUG
logging.level.root=INFO
logging.level.org.springframework=INFO
# Show full stack traces
server.error.include-stacktrace=always
server.error.include-message=always