spring.application.name=microloan-platform

postgres.jdbc.url=jdbc:postgresql://localhost:5432/microloan_platform
postgres.jdbc.username=postgres
postgres.jdbc.password=postgres
postgres.jdbc.driver=org.postgresql.Driver
postgres.jdbc.pool.size=20
postgres.jdbc.query.timeout.sec=40
postgres.jdbc.time.between.eviction.runs.millis=30000
logging.level.org.springframework=DEBUG
flyway.baseline-on-migrate=true

certstore.proteus.endpoint=https://sb1-god-cipher.mum1-pp.zetaapps.in/proteus/zeta.in
sessions.proteus.endpoint=https://sb1-god-cipher.mum1-pp.zetaapps.in/proteus/zeta.in
app.name=${spring.application.name}

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baselineOnMigrate=true
spring.flyway.baselineVersion=1